version: '3.8'
services:
  db: 
    image: mysql:latest
    container_name: Esis_shin_db
    restart: always
    ports: 
      - 3306:3306
    networks:
      - Esis_shin_network
    environment: 
      - MYSQL_DATABASE=Esis_shin
      - MYSQL_ROOT_PASSWORD=bffunlimited123
    volumes:
      - db-data:/var/lib/mysql

  mssql: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shin_mssql
    restart: always
    ports: 
      - 9999:1143
    networks:
      - Esis_shin_network
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=microsoft-squirrel-army

  iam:
    image: rovict.azurecr.io/esisshin-iam:latest-dev
    ports:
      - 7200:80
      - 7201:443
    networks:
      - Esis_shin_network
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Default=Server=mssql;Database=Esis.Iam;User ID=sa;Password=microsoft-squirrel-army;MultipleActiveResultSets=true
      - Clients__EsisShinBff__ClientId=EsisShin
      - Clients__EsisShinBff__ClientSecret=ShinMegamiTensei
      - Clients__EsisShinBff__Uri=https://localhost:5001
    volumes:
      - .keys/iam:/root/.aspnet/DataProtection-Keys

  client: 
    build: 
      context: ./client
    container_name: Esis_shin_client
    command: npm run dev
    ports: 
      - 3000:3000
    networks:
      - Esis_shin_network

  server: 
    build: 
      context: ./Server
      dockerfile: Bff.WebApi/Dockerfile
    container_name: Esis_shin_server
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=bff123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Bff.WebApi.pfx
      - Authentication__ClientId=EsisShin
      - Authentication__ClientSecret=ShinMegamiTensei
      - Authentication__ExternalUrl=https://localhost:7201
      - Authentication__InternalUrl=http://iam
      - FrontEnd=http://host.docker.internal:3000
    networks:
      - Esis_shin_network
    volumes:
      - ~/.aspnet/https:/https:ro
      - .keys/bff:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db
      - iam

volumes:
  db-data:
  
networks:
  Esis_shin_network:
    name: Esis_shin_network